#!/bin/bash

source ./common.sh

# Function to handle the "help" command
function show_help() {
  custom_echo "Usage: eparts [command]"
  custom_echo "====================================="
  custom_echo "Commands:"
  custom_echo "  command1   Test command1"
  custom_echo "  uninstall  Uninstall the CLI"
  custom_echo "  help       Show this help message"
}

# Function to handle the "command1" command
function command1() {
  custom_echo "Executing command1..."
  # Add your command1 logic here
}

# Function to handle the "uninstall" command
function uninstall() {
  echo "Uninstalling CLI..."

  rm -rf "$INSTALL_DIR"
  sed -i '/export PATH="$HOME\/.eparts_cli\/bin:$PATH"/d' "$HOME/.bashrc"
  
  echo "CLI uninstalled successfully."
}

# Main script logic
if [[ $# -eq 0 ]]; then
  show_help
  exit 0
fi

case $1 in
  uninstall)
    uninstall
    ;;
  command1)
    command1
    ;;
  help)
    show_help
    ;;
  *)
    echo "Unknown command: $1"
    show_help
    ;;
esac